### ISSUE TITLE
Query is cancelled by itself after about 20minutes

### ISSUE THREAD

**Issue by innovia** [awslabs/amazon-redshift-utils#174]
Hi

When I attempted to run (twice) the script using the following flags the script terminated saying it was terminated by a user request 

```
python redshift_compression.py \
	--db=my-db \
	--db-user=user \
	--db-pwd='PASSWORD' \
	--db-host=host.us-west-2.redshift.amazonaws.com \
	--db-port=5439 \
	--output-file=redshift-compression.log \
	--report-file=redhift_compression_resport.txt \
	--do-execute=True  \
	--force=True \
	--drop-old-data=False \
	--analyze-table=compression_src_test
```

```
Traceback (most recent call last):
  File "redshift_compression.py", line 379, in run_commands
    cursor.execute(c)
  File "/Users/ami/ltx/virtual_envs/redshift/lib/python2.7/site-packages/pg8000/core.py", line 906, in execute
    self._c.execute(self, operation, args)
  File "/Users/ami/ltx/virtual_envs/redshift/lib/python2.7/site-packages/pg8000/core.py", line 2011, in execute
    self.handle_messages(cursor)
  File "/Users/ami/ltx/virtual_envs/redshift/lib/python2.7/site-packages/pg8000/core.py", line 2088, in handle_messages
    raise self.error
ProgrammingError: (u'ERROR', u'57014', u"Query (4777555) cancelled on user's request", u'/home/ec2-user/padb/src/sys/xen_execute.cpp', u'6574', u'pg_throw', u'', u'')

Error in worker thread: return code 1. Exiting.
```

**Comment by innovia** [comment]
never mind - I found in the script the timeout for the timeout 
 set_timeout = "set statement_timeout = '1200000'"' which is in milliseconds and is 20minutes

**Comment by HaykManukyanAvetiky** [comment]
Hi
Are you using redshift_connector ??
