### ISSUE TITLE
Docker utility not working in Windows

### ISSUE THREAD

**Issue by ksathya** [awslabs/amazon-redshift-utils#228]
If I try the docker workflow to get the "unload and copy" utility working, it fails with the error that "package boto" cannot be found. 

I, then added boto to the requirements.txt after which the docker build process installed it in the container. But at this point I'm getting the following error when I try something like:

docker run --net host -it -e CONFIG_FILE=s3://...... amazon-redshift-utils unload-copy

Running unload-copy utility
Traceback (most recent call last):
  File "UnloadCopyUtility/redshift-unload-copy.py", line 232, in <module>
    main(sys.argv)
  File "UnloadCopyUtility/redshift-unload-copy.py", line 148, in main
    s3Client = boto.s3.connect_to_region(region)
  File "/usr/local/lib/python2.7/site-packages/boto/s3/__init__.py", line 75, in connect_to_region
    connection_cls=S3Connection, **kw_params)
  File "/usr/local/lib/python2.7/site-packages/boto/regioninfo.py", line 220, in connect
    return region.connect(**kw_params)
  File "/usr/local/lib/python2.7/site-packages/boto/s3/__init__.py", line 44, in connect
    return self.connection_cls(host=self.endpoint, **kw_params)
  File "/usr/local/lib/python2.7/site-packages/boto/s3/connection.py", line 194, in __init__
    validate_certs=validate_certs, profile_name=profile_name)
  File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 569, in __init__
    host, config, self.provider, self._required_auth_capability())
  File "/usr/local/lib/python2.7/site-packages/boto/auth.py", line 1021, in get_auth_handler
    'Check your credentials' % (len(names), str(names)))
boto.exception.NoAuthHandlerFound: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV1Handler'] Check your credentials
Done

I'm very new to using Docker so it's likely that I might be doing something stupid, but I could not able to figure a way out by reading the docs, which should ideally be the case.

**Comment by timjell** [comment]
Closing this issue due to the age of the question. Scripts now based on Python3, boto3, and numerous other upgrades and changes. If any further information becomes available or the issue resurfaces, then please reopen this issue.
