### ISSUE TITLE
Exception 'unpack_from' in ColumnEncoding only with some tables

### ISSUE THREAD

**Issue by cosenal** [awslabs/amazon-redshift-utils#239]
I've just cloned from the _master_ branch and am using the ColumnEncoding script through Docker by running 
```
docker run --net host --rm -it --env-file scaling-test.env amazon-redshift-utils column-encoding
```
For some of the Redshift tables, I get the following error:
```
-- [6] [6] Running insert into public."example_table_$mig"  select * from public."example_table" order by timestamp;
Exception unpack_from requires a buffer of at least 5 bytes during analysis of example_table
Traceback (most recent call last):
  File "ColumnEncodingUtility/analyze-schema-compression.py", line 788, in analyze
    if not run_commands(get_pg_conn(), statements):
  File "ColumnEncodingUtility/analyze-schema-compression.py", line 383, in run_commands
    conn.rollback()
  File "/usr/local/lib/python2.7/site-packages/pg8000/core.py", line 1545, in rollback
    self.execute(self._cursor, "rollback", None)
  File "/usr/local/lib/python2.7/site-packages/pg8000/core.py", line 1741, in execute
    self.handle_messages(cursor)
  File "/usr/local/lib/python2.7/site-packages/pg8000/core.py", line 1875, in handle_messages
    code, data_len = ci_unpack(self._read(5))
error: unpack_from requires a buffer of at least 5 bytes
```

I haven't identified any pattern among the tables that cause the issue.

**Comment by emirot** [comment]
I've the same issue, it looks to be related to pg8000

**Comment by IanMeyers** [comment]
Can you give me a definition of the table in question, along with rowcounts etc?

**Comment by IanMeyers** [comment]
Please note https://github.com/mfenniak/pg8000/issues/119

**Comment by IanMeyers** [comment]
What platform/chipset are you running docker on?

**Comment by cosenal** [comment]
@IanMeyers I am running Docker `Version 17.12.0-ce-mac46 (21698)` on MacOS High Sierra on a last-generation MacBook Pro.
I will follow up soon with a definition of the table that makes the script fail.

**Comment by IanMeyers** [comment]
OK - great. Can you just run that command through psql or a client tool and let us know what you see?

**Comment by emirot** [comment]
Using postico I get  : 
Running this query 
```
 SELECT 'vacuum FULL ' + feedback_tbl.schema_name + '."' + feedback_tbl.table_name + '" ; ' 
                       + '/* Size : ' + CAST(info_tbl."size" AS VARCHAR(10)) + ' MB' 
                       + ', Unsorted_pct : ' + coalesce(unsorted :: varchar(10),'null') 
                       + ', Stats Off : ' + stats_off :: varchar(10)
                       + ' */ ;' as statement,
                       table_name
                FROM (SELECT schema_name,
                             table_name
                      FROM (SELECT TRIM(n.nspname) schema_name,
                                   TRIM(c.relname) table_name,
                                   DENSE_RANK() OVER (ORDER BY COUNT(*) DESC) AS qry_rnk,
                                   COUNT(*)
                            FROM stl_alert_event_log AS l
                              JOIN (SELECT query,
                                           tbl,
                                           perm_table_name
                                    FROM stl_scan
                                    WHERE perm_table_name <> 'Internal Worktable'
                                    GROUP BY query,
                                             tbl,
                                             perm_table_name) AS s ON s.query = l.query
                              JOIN pg_class c ON c.oid = s.tbl
                              JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
                            WHERE l.userid > 1
                            AND   l.event_time >= dateadd(DAY,-1,CURRENT_DATE)
                            AND   regexp_instr(solution,'.*VACUUM.*') > 0
                            GROUP BY TRIM(n.nspname),
                                     TRIM(c.relname)) anlyz_tbl
                      WHERE anlyz_tbl.qry_rnk <25) feedback_tbl
                  JOIN svv_table_info info_tbl
                    ON info_tbl.schema = feedback_tbl.schema_name
                   AND info_tbl.table = feedback_tbl.table_name
                WHERE (info_tbl.unsorted > 5 OR info_tbl.stats_off > 10)
                AND   info_tbl.size < (700*1024)
                AND   TRIM(info_tbl.schema) = 'analytics'
                ORDER BY info_tbl.size,
                         info_tbl.skew_rows
```
I get : 

```
vacuum FULL analytics."vehicle_search_index_history" ; /* Size : 156 MB, Unsorted_pct : null, Stats Off : 10.15 */ ;	vehicle_search_index_history
vacuum FULL analytics."driver_summary" ; /* Size : 2004 MB, Unsorted_pct : null, Stats Off : 50.51 */ ;	driver_summary
vacuum FULL analytics."reservation_summary" ; /* Size : 2436 MB, Unsorted_pct : 50.02, Stats Off : 50.32 */ ;	reservation_summary
vacuum FULL analytics."vehicle_summary" ; /* Size : 2508 MB, Unsorted_pct : 50.02, Stats Off : 50.38 */ ;	vehicle_summary
```

**Comment by emirot** [comment]
@IanMeyers I've tested on a Docker `Version 17.09.0-ce-mac35 (19611)
Channel: stable
a98b7c1b7c` doing the same thing on the same schema worked on most of the table but I had the issue at some point.

**Comment by cosenal** [comment]
I have tested it outside Docker and it doesn't break.

**Comment by IanMeyers** [comment]
So I can reproduce this now, but the error doesn't occur with version 1.10.5 of pg8000. Can you please update requirements.txt `pg8000==1.10.5` and then rebuild your docker package: `docker build -t amazon-redshift-utils .` and let me know if the issue goes away for you?

**Comment by cosenal** [comment]
I rebuilt the docker image after downgrading pg8000, but the error is still there. It's shown without a traceback, the phrasing of the reporting and the way the code is aborted are slightly different, but the error itself seems to be still there.

`pg8000==1.11.0`:
```
-- [7] [7] Running insert into public."page_views_y1_$mig"  select * from public."page_views_y1" order by timestamp;
Exception unpack_from requires a buffer of at least 5 bytes during analysis of page_views_y1
Traceback (most recent call last):
  File "ColumnEncodingUtility/analyze-schema-compression.py", line 787, in analyze
    if not run_commands(get_pg_conn(), statements):
  File "ColumnEncodingUtility/analyze-schema-compression.py", line 382, in run_commands
    conn.rollback()
  File "/usr/local/lib/python2.7/site-packages/pg8000/core.py", line 1545, in rollback
    self.execute(self._cursor, "rollback", None)
  File "/usr/local/lib/python2.7/site-packages/pg8000/core.py", line 1741, in execute
    self.handle_messages(cursor)
  File "/usr/local/lib/python2.7/site-packages/pg8000/core.py", line 1875, in handle_messages
    code, data_len = ci_unpack(self._read(5))
error: unpack_from requires a buffer of at least 5 bytes

Error in worker thread: return code 1. Exiting.
Done
```
error with `pg8000==1.10.5`:
```
-- [7] Analyzing Table 'page_views_y1'
unpack_from requires a buffer of at least 5 bytes
connection is closed
connection is closed
connection is closed
connection is closed
```

**Comment by emirot** [comment]
Without docker it worked as well for me, I tried using different python version in the docker like `2-stretch` or `2-jessie` but it didn't work.

**Comment by emirot** [comment]
I also got the error without using docker.

**Comment by emirot** [comment]
@IanMeyers  I've tested with psycopg2 and it looks to be working : https://github.com/emirot/amazon-redshift-utils/commit/aed36cbe182b4c13196c06384bfcc48709ca2c5f why pg8000 was prefered ?

**Comment by IanMeyers** [comment]
Because pygresql is written in C/C++, it has to be natively compiled for AWS Lambda, which makes these modules very hard to test on Mac and Windows without separate and more complicated build script. Because pg8000 is pure Python, we are able to include the dependency and run anywhere.

**Comment by IanMeyers** [comment]
@emirot Would be great to know where it fails outside of docker.

**Comment by emirot** [comment]
@IanMeyers thanks for the explanation

Example from my logs (without using docker) : 
```
Pushing metrics to CloudWatch failed: exception An error occurred (SignatureDoesNotMatch) when calling the PutMetricData operation: Signature not yet current: 20180217T135352Z is still later than 20180217T134444Z (20180217T133944Z + 5 min.)
-- 2018-02-17 13:53:53.025706 [3678] [3678] Running 71 out of 72 commands: vacuum FULL analytics."search_log_to_impression" ; /* Size : 333673 MB,  Unsorted_pct : 61.37 */ ;
Traceback (most recent call last):
  File "lib/analyze_vacuum.py", line 163, in run_commands
    cursor.execute(c)
  File "/home/ubuntu/anaconda/envs/vacuum/lib/python2.7/site-packages/pg8000/core.py", line 852, in execute
    self._c.execute(self, operation, args)
  File "/home/ubuntu/anaconda/envs/vacuum/lib/python2.7/site-packages/pg8000/core.py", line 1813, in execute
    self.handle_messages(cursor)
  File "/home/ubuntu/anaconda/envs/vacuum/lib/python2.7/site-packages/pg8000/core.py", line 1875, in handle_messages
    code, data_len = ci_unpack(self._read(5))
error: unpack_from requires a buffer of at least 5 bytes
```
I don't understand why it's at the last step ...
The instance is an aws ec2, ubuntu 14.04

**Comment by luben** [comment]
Running this method 2 times in a row results in the same failure on the second invocation:

```python
    def get_partitions(self):
        cursor = self.db_conn.cursor()
        cursor.execute("""
            SELECT table_name
            FROM SVV_TABLES
            WHERE table_schema='public'
              AND table_name ~ '%s_[0-9]{4}_[0-9]{2}'
            ORDER BY table_name
        """ % self.name)
        partitions = [table for [table] in cursor.fetchall()]
        cursor.close()
        return partitions
```
The error on 1.10.6:

```
Traceback (most recent call last):
  File "./ls_schema.py", line 177, in <module>
    main()
  File "./ls_schema.py", line 173, in main
    view.daily_job()
  File "./ls_schema.py", line 117, in daily_job
    x = self.get_partitions()
  File "./ls_schema.py", line 33, in get_partitions
    """ % self.name)
  File "/usr/lib/python2.7/dist-packages/pg8000/core.py", line 906, in execute
    self._c.execute(self, operation, args)
  File "/usr/lib/python2.7/dist-packages/pg8000/core.py", line 2013, in execute
    self.handle_messages(cursor)
  File "/usr/lib/python2.7/dist-packages/pg8000/core.py", line 2083, in handle_messages
    code, data_len = ci_unpack(self._read(5))
struct.error: unpack_from requires a buffer of at least 5 bytes
```
I get the same error with using 1.10.2 also.

Both of the versions are from Ubuntu repos (16.04). No docker or VMs.

**Comment by gmanolache** [comment]
I'm receiving the same exception after having run the script from the docker image:
```
Exception unpack_from requires a buffer of at least 5 bytes during analysis of mytable
Traceback (most recent call last):
  File "analyze-schema-compression.py", line 845, in analyze
    if not run_commands(get_pg_conn(), statements):
  File "analyze-schema-compression.py", line 440, in run_commands
    conn.rollback()
  File "/usr/local/lib/python2.7/site-packages/pg8000/core.py", line 1545, in rollback
    self.execute(self._cursor, "rollback", None)
  File "/usr/local/lib/python2.7/site-packages/pg8000/core.py", line 1741, in execute
    self.handle_messages(cursor)
  File "/usr/local/lib/python2.7/site-packages/pg8000/core.py", line 1875, in handle_messages
    code, data_len = ci_unpack(self._read(5))
error: unpack_from requires a buffer of at least 5 bytes
```

**Comment by gmanolache** [comment]
I'm running the docker container inside macOS on a MacBook Pro.

**Comment by florianeichin** [comment]
is there any update? How did you solve this issue?

**Comment by florianeichin** [comment]
This seems to be a timing issue. If I  wait a few seconds after the docker container starts up, this error doesn't appear.

**Comment by saeedma8** [comment]
[Amazon Redshift Column Encoding Utility](https://github.com/awslabs/amazon-redshift-utils/tree/master/src/ColumnEncodingUtility#amazon-redshift-column-encoding-utility) is now deprecated. Instead, please use Redshift's Automatic Table Optimization features through:

```
ALTER TABLE table_name ALTER SORTKEY AUTO;
ALTER TABLE table_name ALTER DISTSTYLE AUTO;
```

https://docs.aws.amazon.com/redshift/latest/dg/t_Creating_tables.html

**Comment by ShumzZzZz** [comment]
Is there any update on this?

I submitted a Sklearn or Pyspark processing job to AWS SageMaker; inside the job, I used `redshfit_connector` to query (simple select, nothing fancy) some tables (it could happen to any table, not any specific table). With the exact same code and no changes made to the queried tables, this job could fail with the same error msg:
```
....
File "/usr/local/lib/python3.9/site-packages/redshift_connector/cursor.py", line 229, in execute
    self._c.execute(self, "begin transaction", None)
  File "/usr/local/lib/python3.9/site-packages/redshift_connector/core.py", line 1718, in execute
    self.handle_messages(cursor)
  File "/usr/local/lib/python3.9/site-packages/redshift_connector/core.py", line 1982, in handle_messages
    code, data_len = ci_unpack(self._read(5))
```
struct.error: unpack_from requires a buffer of at least 5 bytes for unpacking 5 bytes at offset 0 (actual buffer size is 0)
