### ISSUE TITLE
analyze-schema-compression.py gets pg8000 zero-length delimited identifier at or near """"

### ISSUE THREAD

**Issue by bboad** [awslabs/amazon-redshift-utils#374]
Using ColumnEncodingUtility-v.9.3.4 with pg8000==1.11.0 (also tried newer pg8000)

When attempting to process any table with 1 or more sort key columns we get a 

python $BIN_DIR/analyze-schema-compression.py  --db $DB --db-user $DBUSER --db-pwd $DBPWD --db-port $DBPORT --db-host $DBHOST --ssl-option true --analyze-schema $SCHEMALIST --analyze-table $TABLIST --do-execute true --output-file $LOG 

Traceback (most recent call last):
  File "/home/ec2-user/amazon-redshift-utils-master/src/ColumnEncodingUtility/analyze-schema-compression.py", line 436, in run_commands
    cursor.execute(c)
  File "/usr/local/lib/python2.7/site-packages/pg8000/core.py", line 892, in execute
    self._c.execute(self, operation, args)
  File "/usr/local/lib/python2.7/site-packages/pg8000/core.py", line 1849, in execute
    self.handle_messages(cursor)
  File "/usr/local/lib/python2.7/site-packages/pg8000/core.py", line 1988, in handle_messages
    raise self.error
ProgrammingError: (u'ERROR', u'42601', u'zero-length delimited identifier at or near """"', u'90', u'/home/ec2-user/padb/src/pg/src/backend/parser/parser_scan.l', u'707', u'yyerror')

It works for any schema/table that has no defined sort key.

**Comment by bboad** [comment]
This issue looks to be addressed by this recent commit by kevinviraudDH:

https://github.com/awslabs/amazon-redshift-utils/pull/364/commits/b25276c842f70bb7b7d0d09bbaad584229efbd09

**Comment by timjell** [comment]
Closed due to commit as noted above
