### ISSUE TITLE
AnalyzeVacuumUtility - Not running

### ISSUE THREAD

**Issue by BhuviTheDataGuy** [awslabs/amazon-redshift-utils#495]
I have downloaded the AnalyzeVacuumUtility, when I try to run, it's triggered and ends immediately. 

The command I used:

```sh
python analyze-vacuum-schema.py  --db prod --db-user admin--db-pwd mypass --db-port 5439 --db-host redshift-cluster-south-1.redshift.amazonaws.com    --output-file /tmp/test.log --debug True  --ignore-errors False --slot-count 1
```

### Log file:

```
 -- 2020-04-12 01:38:24.177698 [30231] Connected to CloudWatch in us-east-1
-- 2020-04-12 01:38:24.177801 [30231] Using Cluster Name redshift-cluster
-- 2020-04-12 01:38:24.177811 [30231] Supplied Args:
{'db': 'prod', 'db_pwd': 'mypass', 'db_port': 5439, 'db_user': 'admin', 'db_host': 'redshift-cluster.cdo9igponfzt.ap-south-1.redshift.amazonaws.com', 'debug': True, 'query_slot_count': 1}
-- 2020-04-12 01:38:24.177886 [30231] Connect redshift-cluster.cdo9igponfzt.ap-south-1.redshift.amazonaws.com:5439:prod:redshift-cluster
-- 2020-04-12 01:38:24.196737 [30231] set statement_timeout = '36000000'
-- 2020-04-12 01:38:24.196766 [30231] [30231] Running 1 out of 1 commands: set statement_timeout = '36000000'
-- 2020-04-12 01:38:24.199024 [30231] Success.
-- 2020-04-12 01:38:24.199040 [30231] set application_name to 'AnalyzeVacuumUtility-v.9.1.6'
-- 2020-04-12 01:38:24.199049 [30231] [30231] Running 1 out of 1 commands: set application_name to 'AnalyzeVacuumUtility-v.9.1.6'
-- 2020-04-12 01:38:24.201311 [30231] Success.
-- 2020-04-12 01:38:24.201324 [30231] Connected to redshift-cluster.cdo9igponfzt.ap-south-1.redshift.amazonaws.com:5439:prod as redshift-cluster
-- 2020-04-12 01:38:24.201332 [30231] Vacuum flag arg is not set. Vacuum not performed.
-- 2020-04-12 01:38:24.201340 [30231] Analyze flag arg is set as False. Analyze is not performed.
-- 2020-04-12 01:38:24.201345 [30231] Processing Complete
```

**Comment by IanMeyers** [comment]
Please add either `--analyze-flag`, `--vacuum-flag`, or both to turn on the types of operations you require. However these operations are now either fully or partially performed automatically:

* https://aws.amazon.com/about-aws/whats-new/2019/01/amazon-redshift-auto-analyze/
* https://aws.amazon.com/about-aws/whats-new/2019/11/amazon-redshift-introduces-automatic-table-sort-alternative-vacuum-sort/

For certain use cases, you may still want to schedule a vacuum operation, but analyse should be covered.

**Comment by BhuviTheDataGuy** [comment]
Im getting this error now.

```
Traceback (most recent call last):
  File "analyze-vacuum-schema.py", line 50, in <module>
    import analyze_vacuum
  File "lib/analyze_vacuum.py", line 20, in <module>
    import aws_utils
  File "/usr/local/lib/python2.7/dist-packages/aws_utils/__init__.py", line 4, in <module>
    from .sqs_consumer import SQSConsumer  # noqa
  File "/usr/local/lib/python2.7/dist-packages/aws_utils/sqs_consumer.py", line 4, in <module>
    from .exceptions import MissingQueueError
ImportError: cannot import name MissingQueueError
```

I have cloned the complete repo and installed all the packages.

**Comment by IanMeyers** [comment]
Can you please invoke the command from the `src` directory, as:

```
python3 AnalyzeVacuumUtility/analyze-vacuum-schema.py arg1, arg2, arg3
```

**Comment by BhuviTheDataGuy** [comment]
Still its throwing the same error.

```
/tmp/rs/amazon-redshift-utils/src# python AnalyzeVacuumUtility/analyze-vacuum-schema.py  --db prod --db-user xxxxx --db-pwd xxxxxx --db-port 5439 --db-host xxxxxx.cdo9igponfzt.ap-south-1.redshift.amazonaws.com --schema-name public  --table-name test --output-file /tmp/test.log --debug True  --ignore-errors False --slot-count 2 --min-unsorted-pct 5 --max-unsorted-pct 50 --stats-off-pct 10  --vacuum-flag


Traceback (most recent call last):
  File "AnalyzeVacuumUtility/analyze-vacuum-schema.py", line 50, in <module>
    import analyze_vacuum
  File "AnalyzeVacuumUtility/lib/analyze_vacuum.py", line 20, in <module>
    import aws_utils
  File "/usr/local/lib/python2.7/dist-packages/aws_utils/__init__.py", line 4, in <module>
    from .sqs_consumer import SQSConsumer  # noqa
  File "/usr/local/lib/python2.7/dist-packages/aws_utils/sqs_consumer.py", line 4, in <module>
    from .exceptions import MissingQueueError
ImportError: cannot import name MissingQueueError
```

**Comment by IanMeyers** [comment]
Have you installed dependencies? From folder root, do `pip install -r requirements.txt --user`.

**Comment by BhuviTheDataGuy** [comment]
Yes I did

```
pip install -r requirements.txt --user
Requirement already satisfied: wheel==0.24.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: pg8000==1.11.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: shortuuid==0.4.3 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied: six==1.10.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied: boto3==1.5.3 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 5))
Requirement already satisfied: pgpasslib==1.1.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 6))
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /usr/local/lib/python2.7/dist-packages (from boto3==1.5.3->-r requirements.txt (line 5))
Requirement already satisfied: botocore<1.9.0,>=1.8.17 in /usr/local/lib/python2.7/dist-packages (from boto3==1.5.3->-r requirements.txt (line 5))
Requirement already satisfied: s3transfer<0.2.0,>=0.1.10 in /usr/local/lib/python2.7/dist-packages (from boto3==1.5.3->-r requirements.txt (line 5))
Requirement already satisfied: docutils>=0.10 in /usr/local/lib/python2.7/dist-packages (from botocore<1.9.0,>=1.8.17->boto3==1.5.3->-r requirements.txt (line 5))
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python2.7/dist-packages (from botocore<1.9.0,>=1.8.17->boto3==1.5.3->-r requirements.txt (line 5))
Requirement already satisfied: futures<4.0.0,>=2.2.0; python_version == "2.6" or python_version == "2.7" in /usr/local/lib/python2.7/dist-packages (from s3transfer<0.2.0,>=0.1.10->boto3==1.5.3->-r requirements.txt (line 5))
```

**Comment by IanMeyers** [comment]
Can you please try to update your version of boto3? I can't reproduce the issue you are reporting...

**Comment by IanMeyers** [comment]
Can I please ask everyone to update to version .9.2.0. Arg parsing was a mess in this code and I've now cleaned it up and I hope it will be more reliable for everyone. I am able to run the module without issue:

```
python3 AnalyzeVacuumUtility/analyze-vacuum-schema.py --analyze-flag True --db-user=master --db=master --db-host=localhost --db-port=5439 --db-pwd=XXXXX
-- 2020-04-13 17:28:16.072089 [43085] Connected to CloudWatch in us-east-1
-- 2020-04-13 17:28:16.299700 [43085] [43085] Running 1 out of 1 commands: set statement_timeout = '36000000'
-- 2020-04-13 17:28:16.343612 [43085] Success.
-- 2020-04-13 17:28:16.343748 [43085] [43085] Running 1 out of 1 commands: set application_name to 'AnalyzeVacuumUtility-v.9.2.0'
-- 2020-04-13 17:28:16.389617 [43085] Success.
-- 2020-04-13 17:28:16.389679 [43085] Connected to localhost:5439:master as master
-- 2020-04-13 17:28:16.389724 [43085] Extracting Candidate Tables for Vacuum...
-- 2020-04-13 17:28:28.246869 [43085] Found 0 Tables requiring Vacuum and flagged by alert
-- 2020-04-13 17:28:28.246931 [43085] Extracting Candidate Tables for Vacuum ...
-- 2020-04-13 17:28:37.744727 [43085] Found 0 Tables requiring Vacuum due to stale statistics
-- 2020-04-13 17:28:37.744781 [43085] Extracting Candidate Tables for Vacuum reindex of Interleaved Sort Keys...
-- 2020-04-13 17:29:05.807412 [43085] Found 0 Tables with Interleaved Sort Keys requiring Vacuum
-- 2020-04-13 17:29:05.807471 [43085] Extracting Candidate Tables for analyze based on Query Optimizer Alerts...
-- 2020-04-13 17:29:22.636433 [43085] Found 0 Tables requiring Analysis
-- 2020-04-13 17:29:22.636518 [43085] Extracting Candidate Tables for analyze based on stats off from system table info ...
-- 2020-04-13 17:29:32.264008 [43085] Processing Complete
```

**Comment by ifenglin** [comment]
I can reproduce this issue when I was running https://github.com/awslabs/amazon-redshift-utils/blob/master/src/test.py 

It looks like that the first line `import aws_utils` can mistakenly refer to the library `aws_utils` on PyPI. The same occurred at https://github.com/awslabs/amazon-redshift-utils/blob/master/src/AnalyzeVacuumUtility/lib/analyze_vacuum.py#L20 in an earlier version. That's why it affects AnalyzeVacuumUtility.

**Comment by timjell** [comment]
AnalyzeVacuum has had many updates since this issue. I can not reproduce the issue, and the code reported above is now showing as:

`import redshift_utils_helper as aws_utils`
