### ISSUE TITLE
SimpleReplay doesn't work with database usernames with multiple dashes

### ISSUE THREAD

**Issue by jsyrjala** [awslabs/amazon-redshift-utils#544]
We have a Redshift username like this `xxxxxxxx-xxxxxx-xxxxxx-xxxx`  consisting letters and dashes. Running replay.py fails with this kind of error.

```
python3 replay.py replay.yaml
[ERROR] 2021-04-06 09:31:24 Config file missing value for "odbc_driver". Therefore, replay will not use ODBC, and will use psql instead. Please provide a value for "odbc_driver" if playback using ODBC instead of psql is necessary.
[INFO] 2021-04-06 09:31:24 Found 403 total connections, 0 don't match filters. Replaying 403.
[INFO] 2021-04-06 09:31:24 Loading transactions from my-workload/Extraction_2021-04-06T08:54:17.054408+00:00, this might take some time.
Traceback (most recent call last):
  File "replay.py", line 1583, in <module>
    main()
  File "replay.py", line 1411, in main
    possible_connections = connection_idx_by_key[connection_key]
KeyError: 'dbname_foo_bar'
```

**Comment by ragsrina** [comment]
This has been addressed in the release 2.1.4 Please, provide us with any feedback you have on the latest release.
